### ISSUE TITLE
소울스톤 이미지

### ISSUE THREAD

**Issue by rockpell** [rockpell/HealingSpace#13]
소울 스톤 이미지는 우주와 상점에서 사용됩니다.

우주에서는 화면에 떠다니는 용도로 상점에서는 재화의 역할을 합니다.

종류
- 다크 스톤
- 레드 스톤
- 블루 스톤
- 화이트 스톤

**Comment by mimseong** [comment]
우주에서 떠다니는 이미지와 상점이나 UI에 쓰이는 이미지를 분리하면 좋을 것 같습니다
상점 & UI에 쓰이는 이미지는 해상도를 낮춰서 제작할게요
@blingblin-g @rockpell

**Comment by mimseong** [comment]
![image](https://user-images.githubusercontent.com/50068946/95336697-ec50ff00-08eb-11eb-9309-334efabed22c.png)

제작 완료했습니다!
떠다니는 소울과 구분하기 위해서 일부러 단순하게 제작했습니다
