### ISSUE TITLE
상태 UI 제작

### ISSUE THREAD

**Issue by rockpell** [rockpell/HealingSpace#14]
- 이름, 레벨, 체력, 소울스톤 갯수를 표시하는 UI 제작
- 이름, 레벨, 체력은 평소에 보이지 않다가 각 캐릭터를 선택하면 나타난다.
- 소울 스톤 갯수는 항상 표시된다.

**Comment by blingblin-g** [comment]
UI completed! (need 'heart' images, pretty retro-font)
