### ISSUE TITLE
하트이미지

### ISSUE THREAD

**Issue by rockpell** [rockpell/HealingSpace#15]
아래의 스크린샷에서 보이는 하트가 소울스톤처럼 입체적으로 보이면 좋을거 같아요.

![image](https://user-images.githubusercontent.com/8137615/94698988-ce781d00-0374-11eb-9064-2620f4cdd581.png)

**Comment by mimseong** [comment]
넵!! 만들겠습니다

**Comment by mimseong** [comment]
완료했습니다
